name: test-conda-env-py3
channels:
- conda-forge
- nodefaults
dependencies:
- git
- numpy
- libhwloc=2
# pocl 3.1 needed for SVM functionality
# pocl<7 because of https://github.com/inducer/grudge/issues/396
- pocl>=3.1,<7
- islpy
- pyopencl
- python=3
- gmsh
- jax

# test scripts use ompi-specific arguments
- openmpi
- mpi4py
